### ISSUE TITLE
Module not found: Can't resolve 'module'

### ISSUE THREAD

**Issue by FranciscoJBrito** [bm777/nextron-speed-launch#1]
Hi @bm777 👋🏻, these days I have been working on the implementation of v8-snapshots, I was able to add it correctly to the project, but when using it I get an error when requiring 'module'. I have been trying to solve it, if you have any suggestion it would be of great help.
This is the error I get in the terminal:

```shell
./v8-snapshots-util.js:6:17
Module not found: Can't resolve 'module'
  4 |   console.log('snapshotResult available!', snapshotResult)
  5 | 
> 6 |   const Module = require('module')
    |                 ^
  7 |   const entryPointDirPath = path.resolve(
  8 |     global.require.resolve('react'),
  9 |     '..',

Import trace for requested module:
./pages/_app.jsx

https://nextjs.org/docs/messages/module-not-found 
```

**Comment by bm777** [comment]
@FranciscoJBrito 
I will have a look at it today. I have no idea. I will add you as a collaborator to the repository.

**Comment by FranciscoJBrito** [comment]
Thanks @bm777, [here is the code](https://gist.github.com/FranciscoJBrito/ad7a62955dfb95ef11805629bdd98ebc) from which I get the error.
